const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs'),os=require('os'),path=require('path'),http=require('http');let base,server,dataDir,adminCookie,opCookie,sellerCookie;
const cookie=r=>(r.headers.get('set-cookie')||'').split(';')[0];async function req(p,{method='GET',body,cookie:c}={}){const r=await fetch(base+p,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(c?{Cookie:c}:{})},body:body!==undefined?JSON.stringify(body):undefined});return{status:r.status,body:await r.json().catch(()=>null),headers:r.headers}}
async function login(u,p){const r=await req('/api/auth/login',{method:'POST',body:{username:u,password:p}});assert.equal(r.status,200);return cookie({headers:r.headers})}
test.before(async()=>{dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'life-commercial-'));process.env.LIFESUCOS_DATA_DIR=dataDir;for(const m of ['../db','../auth','../app','../commercialRoutes','../logisticsRoutes','../aionAgentRoutes','../routes','../stockRoutes','../services/inventoryService'])try{delete require.cache[require.resolve(m)]}catch{}const{createApp}=require('../app');server=http.createServer(createApp());await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;adminCookie=await login('admin','TestAdmin-v15-Only');opCookie=await login('operador','TestOperator-v15-Only');const create=await req('/api/users',{method:'POST',cookie:adminCookie,body:{nome:'Vendedor Teste',username:'vendtest',perfil:'Vendedor',password:'vend1234'}});assert.equal(create.status,201);sellerCookie=await login('vendtest','vend1234')});
test.after(async()=>{if(server)await new Promise(r=>server.close(r));if(dataDir)fs.rmSync(dataDir,{recursive:true,force:true})});

test('vendedor cadastra cliente e operador enxerga pendência',async()=>{const c=await req('/api/commercial/customers',{method:'POST',cookie:sellerCookie,body:{nome:'Cliente Pendente',cnpj:'12345678000199'}});assert.equal(c.status,201);assert.equal(c.body.statusAprovacao,'pendente');const p=await req('/api/commercial/customers/pending',{cookie:opCookie});assert.equal(p.status,200);assert.ok(p.body.some(x=>x.id===c.body.id));globalThis.clientId=c.body.id});

test('cliente amarelo não aceita boleto',async()=>{const a=await req(`/api/commercial/customers/${globalThis.clientId}/approve`,{method:'POST',cookie:opCookie,body:{classificacao:'Amarelo',tabelaPrecoId:'price_01'}});assert.equal(a.status,200);const price=await req('/api/commercial/price-tables/price_01',{method:'PUT',cookie:adminCookie,body:{nome:'Tabela 01',tipo:'padrao',precos:{life_100:4.0},ativo:true}});assert.equal(price.status,200);await req('/api/stock/entries',{method:'POST',cookie:opCookie,body:{fornecedor:'Fábrica',itens:[{produtoId:'life_100',quantidade:200,lote:'C1',validade:'2099-01-01'}]}});const order=await req('/api/commercial/orders',{method:'POST',cookie:sellerCookie,body:{clienteId:globalThis.clientId,tabelaPrecoId:'price_01',formaPagamento:'Boleto',itens:[{produtoId:'life_100',quantidade:100,unidadeMovimentacao:'Unidade'}]}});assert.equal(order.status,400);assert.match(order.body.error,/não liberada/i)});

test('cliente verde aprova com reserva e romaneio cria saída com veículo',async()=>{const c=await req('/api/commercial/customers',{method:'POST',cookie:sellerCookie,body:{nome:'Cliente Verde',cnpj:'99887766000155'}});await req(`/api/commercial/customers/${c.body.id}/approve`,{method:'POST',cookie:opCookie,body:{classificacao:'Verde',tabelaPrecoId:'price_01'}});const order=await req('/api/commercial/orders',{method:'POST',cookie:sellerCookie,body:{clienteId:c.body.id,tabelaPrecoId:'price_01',formaPagamento:'Boleto',observacoes:'Entregar pela manhã',itens:[{produtoId:'life_100',quantidade:48,unidadeMovimentacao:'Unidade'}]}});assert.equal(order.status,201);assert.equal(order.body.prazoBoletoDias,7);const st=await req('/api/commercial/stock',{cookie:sellerCookie});const p=st.body.find(x=>x.id==='life_100');assert.equal(p.reservado,48);
  const approved=await req(`/api/commercial/orders/${order.body.id}/approve`,{method:'POST',cookie:opCookie,body:{}});assert.equal(approved.status,200);assert.equal(approved.body.exit,null);assert.equal(approved.body.manifest,null);assert.equal(approved.body.order.status,'aprovado');assert.equal(approved.body.stockMovementDeferred,true);
  const available=await req('/api/commercial/separation/available',{cookie:opCookie});assert.ok(available.body.some(x=>x.id===order.body.id));
  const noLogistics=await req('/api/commercial/separation/manifests',{method:'POST',cookie:opCookie,body:{orderIds:[order.body.id]}});assert.equal(noLogistics.status,400);assert.match(noLogistics.body.error,/motorista/i);
  const vehicle=await req('/api/commercial/vehicles',{method:'POST',cookie:opCookie,body:{veiculo:'Fiorino Teste',placa:'ABC1D23',tipo:'Utilitário',capacidadeKg:650}});assert.equal(vehicle.status,201);assert.equal(vehicle.body.placa,'ABC-1D23');
  const created=await req('/api/commercial/separation/manifests',{method:'POST',cookie:opCookie,body:{orderIds:[order.body.id],motorista:'Motorista Teste',vehicleId:vehicle.body.id,horarioSaida:'2099-01-02T08:00'}});assert.equal(created.status,201);assert.ok(created.body.exitId);assert.equal(created.body.motorista,'Motorista Teste');assert.equal(created.body.placa,'ABC-1D23');const item=created.body.totais.find(x=>x.produtoId==='life_100');assert.equal(item.quantidadeUnidades,48);assert.equal(item.conversao.fardos,2);
  const exits=await req('/api/exits',{cookie:opCookie});const exit=exits.body.find(x=>x.id===created.body.exitId);assert.ok(exit);assert.equal(exit.motorista,'Motorista Teste');assert.equal(exit.placa,'ABC-1D23');assert.equal(exit.origemRomaneio,true);
  const stockAfter=await req('/api/commercial/stock',{cookie:sellerCookie});const after=stockAfter.body.find(x=>x.id==='life_100');assert.equal(after.reservado,0);assert.equal(after.fisico,152);
});

test('somente gerente transfere cliente',async()=>{const sellers=await req('/api/commercial/sellers',{cookie:opCookie});const seller=sellers.body.find(x=>x.username==='vendtest');const opTry=await req(`/api/commercial/customers/${globalThis.clientId}/transfer`,{method:'POST',cookie:opCookie,body:{vendedorId:seller.id}});assert.equal(opTry.status,403);const mgr=await req(`/api/commercial/customers/${globalThis.clientId}/transfer`,{method:'POST',cookie:adminCookie,body:{vendedorId:seller.id}});assert.equal(mgr.status,200)});
